/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Cliente;
import aplicacion.Empleado;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author alumnogreibd
 */
public class VAsistente extends javax.swing.JFrame {
    
    private aplicacion.FachadaAplicacion fa;
    private Empleado asistente;
    
    /**
     * Creates new form VAsistente
     */
    public VAsistente(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        
        ModeloTablaAsistente m = new ModeloTablaAsistente(fa);
        tablaUsu.setModel(m);
        m.setFilas(fa.consultarTodosClientes());
        if (m.getRowCount() > 0) { //Si la tabla tiene elementos
            tablaUsu.setRowSelectionInterval(0, 0);
        }
    }
    
    public VAsistente(aplicacion.FachadaAplicacion fa, Empleado as) {
        this.fa = fa;
        this.asistente = as;
        initComponents();
        
        ModeloTablaAsistente m;
        m = (ModeloTablaAsistente) tablaUsu.getModel();
        m.setFilas(fa.consultarTodosClientes());
        if (m.getRowCount() > 0) { //Si la tabla tiene elementos
            tablaUsu.setRowSelectionInterval(0, 0); 
        }
        if(tablaUsu.getSelectedRow()<0 || tablaUsu.getRowCount()==0){
            btnEditaUsuario.setEnabled(false);
            btnDespachar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textoId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnDespachar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsu = new javax.swing.JTable();
        botonStock = new javax.swing.JButton();
        btnEditaUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Asistentes");

        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre:");

        textoId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIdKeyTyped(evt);
            }
        });

        jLabel2.setText("Id:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDespachar.setText("Despachar");
        btnDespachar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespacharActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevoUsuario.setText("Nuevo usuario");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        tablaUsu.setModel(new ModeloTablaAsistente(fa));
        tablaUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsu);

        botonStock.setText("Añadir Stock");
        botonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStockActionPerformed(evt);
            }
        });

        btnEditaUsuario.setText("Editar usuario");
        btnEditaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoNombre)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDespachar)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditaUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(botonStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnBuscar)
                        .addComponent(textoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDespachar)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevoUsuario)
                    .addComponent(botonStock)
                    .addComponent(btnEditaUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ModeloTablaAsistente m;
        m = (ModeloTablaAsistente) tablaUsu.getModel();
        m.setFilas(fa.consultarClientes(textoNombre.getText(), textoId.getText()));
        if (m.getRowCount() > 0) { //Si la tabla tiene elementos
            tablaUsu.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDespacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespacharActionPerformed
        // TODO add your handling code here:
        if(tablaUsu.getRowCount()==0){
            return;
        }
        if(tablaUsu.getSelectedRow()<0){
            fa.muestraExcepcion("Se debe de seleccionar a un usuario para realizar esta operación");
        }
        else{
            ModeloTablaAsistente m;
            m = (ModeloTablaAsistente) tablaUsu.getModel();
            if(m.getRowCount()>0){
                Cliente c = m.obtenerCliente(tablaUsu.getSelectedRow());
                fa.visualizarDespachar(c, asistente);
            }
        }
    }//GEN-LAST:event_btnDespacharActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        ModeloTablaAsistente m;
        m = (ModeloTablaAsistente) tablaUsu.getModel();
        fa.visualizarCrearUsuario(m);
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        fa.iniciaInterfazUsuario();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void textoIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIdKeyTyped
        // TODO add your handling code here:
        if(textoId.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_textoIdKeyTyped

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        // TODO add your handling code here:
        if(textoNombre.getText().length()>=50)
            evt.consume();
    }//GEN-LAST:event_textoNombreKeyTyped

    private void botonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStockActionPerformed
        fa.abrirStock();
    }//GEN-LAST:event_botonStockActionPerformed

    private void btnEditaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaUsuarioActionPerformed
        if(tablaUsu.getSelectedRow()<0)
            fa.muestraExcepcion("Se debe de seleccionar a un usuario para realizar esta opreación");
        else{
            ModeloTablaAsistente m;
            m = (ModeloTablaAsistente) tablaUsu.getModel();
            if(m.getRowCount()>0){
                Cliente c = m.obtenerCliente(tablaUsu.getSelectedRow());
                fa.iniciaEditarUsuario(c, m);
            }
        }
    }//GEN-LAST:event_btnEditaUsuarioActionPerformed

    private void tablaUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuMouseClicked
        if(tablaUsu.getSelectedRow()>=0){
            btnEditaUsuario.setEnabled(true);
            btnDespachar.setEnabled(true);
        }
            
    }//GEN-LAST:event_tablaUsuMouseClicked
 
    public void desactivaBotones(){
        btnEditaUsuario.setEnabled(false);
        btnDespachar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonStock;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDespachar;
    private javax.swing.JButton btnEditaUsuario;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsu;
    private javax.swing.JTextField textoId;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
