/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Cliente;
import aplicacion.Empleado;
import java.awt.event.KeyEvent;

/**

 @author alumnogreibd
 */
public class VLogin extends javax.swing.JFrame{

    aplicacion.FachadaAplicacion fa;
    
    /**
     Creates new form VLogin
     */
    public VLogin(aplicacion.FachadaAplicacion fa){
        this.fa=fa;
        initComponents();
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AccederPanel = new javax.swing.JPanel();
        ClaveLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        ClienteEmpleadoComboBox = new javax.swing.JComboBox();
        AccederButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        UsuarioLabel = new javax.swing.JLabel();
        AvisosLabel = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");

        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        ClaveLabel.setText("Clave");

        IDLabel.setText("ID");

        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });
        IDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDTextKeyPressed(evt);
            }
        });

        ClienteEmpleadoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ClienteEmpleadoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Asistente", "Reparador", "Jefe" }));
        ClienteEmpleadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteEmpleadoComboBoxActionPerformed(evt);
            }
        });
        ClienteEmpleadoComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClienteEmpleadoComboBoxKeyPressed(evt);
            }
        });

        AccederButton.setText("Acceder");
        AccederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederButtonActionPerformed(evt);
            }
        });

        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        UsuarioLabel.setText("Usuario");

        AvisosLabel.setText(" ");

        javax.swing.GroupLayout AccederPanelLayout = new javax.swing.GroupLayout(AccederPanel);
        AccederPanel.setLayout(AccederPanelLayout);
        AccederPanelLayout.setHorizontalGroup(
            AccederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccederPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccederPanelLayout.createSequentialGroup()
                        .addComponent(AccederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AvisosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                        .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AccederPanelLayout.createSequentialGroup()
                        .addGroup(AccederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuarioLabel)
                            .addComponent(ClaveLabel)
                            .addComponent(ClienteEmpleadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtClave))
                .addContainerGap())
        );
        AccederPanelLayout.setVerticalGroup(
            AccederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccederPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClaveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(UsuarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteEmpleadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(AccederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirButton)
                    .addComponent(AccederButton)
                    .addComponent(AvisosLabel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Acceder", AccederPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void ClienteEmpleadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteEmpleadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteEmpleadoComboBoxActionPerformed

    private void AccederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederButtonActionPerformed
        // TODO add your handling code here:
        String Usuario = ClienteEmpleadoComboBox.getSelectedItem().toString();
        boolean Valido = false;
        if(Usuario.equals("Cliente")){
            AvisosLabel.setText(Usuario+": NO DISPONIBLE EN ESTA VERSIÓN");
        }
        else if(Usuario.equals("Asistente")){
            Empleado as = fa.validarAsistente(IDText.getText(), txtClave.getText());
            if(as != null){
                fa.abrirAsistentes(as);
                this.dispose();
            }
            else{
                AvisosLabel.setText(Usuario+": Credenciales incorrectos");
            }
        }
        else if(Usuario.equals("Reparador")){
            Empleado rep = fa.validarReparador(IDText.getText(), txtClave.getText());
            if(rep != null){
                fa.abrirReparadores(rep);
                this.dispose();
            }
            else{
                AvisosLabel.setText(Usuario+": Credenciales incorrectos");
            }
        }
        else if(Usuario.equals("Jefe")){
            AvisosLabel.setText(Usuario+": NO DISPONIBLE EN ESTA VERSIÓN");
        }
        else{
            AvisosLabel.setText(Usuario+": Credenciales incorrectos");
        }
    }//GEN-LAST:event_AccederButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) AccederButtonActionPerformed(null);
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void IDTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) AccederButtonActionPerformed(null);
    }//GEN-LAST:event_IDTextKeyPressed

    private void ClienteEmpleadoComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteEmpleadoComboBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) AccederButtonActionPerformed(null);
    }//GEN-LAST:event_ClienteEmpleadoComboBoxKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccederButton;
    private javax.swing.JPanel AccederPanel;
    private javax.swing.JLabel AvisosLabel;
    private javax.swing.JLabel ClaveLabel;
    private javax.swing.JComboBox ClienteEmpleadoComboBox;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField txtClave;
    // End of variables declaration//GEN-END:variables
}
