/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Componente;
import aplicacion.*;

/**
 *
 * @author alumnogreibd
 */
public class VStock extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VStock
     */
    public VStock(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        
        this.fa = fa;
        
        ModeloListaStrings mListaC=new ModeloListaStrings();
        listaEjemplar.setModel(mListaC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        comboComponente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcionComponente = new javax.swing.JTextArea();
        textoMarcaComponente = new javax.swing.JTextField();
        textoPrecioComponente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoNombreComponente = new javax.swing.JTextField();
        botonAnadirComponente = new javax.swing.JButton();
        botonSalirComponente = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textoPotenciaAlim = new javax.swing.JTextField();
        comboModularAlim = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        textoSocketsCpu = new javax.swing.JTextField();
        textoCoresCpu = new javax.swing.JTextField();
        textoThreadsCpu = new javax.swing.JTextField();
        textoFrecuenciaCpu = new javax.swing.JTextField();
        textoTdpCpu = new javax.swing.JTextField();
        textoMicroCpu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        textoCapacidadDisco = new javax.swing.JTextField();
        textoVelocidadDisco = new javax.swing.JTextField();
        comboTipoDisco = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        textoFrecuenciaGpu = new javax.swing.JTextField();
        textoProcesoGpu = new javax.swing.JTextField();
        jlabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        textoNucleosGpu = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textoTipoPerif = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        textoChipsetPlaca = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        textoTamanoPlaca = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        textoMemoriaRam = new javax.swing.JTextField();
        textoFrecuenciaRam = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        comboTipoRam = new javax.swing.JComboBox();
        comboFormatoRam = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textoTamanoRefri = new javax.swing.JTextField();
        comboTipoRefri = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        textoNombrePC = new javax.swing.JTextField();
        textoPrecioPC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonSalirPC = new javax.swing.JButton();
        botonAnadirPC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comboComponenteEjemplar = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEjemplar = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        botonSalirEjemplar = new javax.swing.JButton();
        botonAnadirEjemplar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Stock");

        comboComponente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentación", "CPU", "Disco duro", "GPU", "Periférico", "Placa base", "RAM", "Refrigeración" }));
        comboComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComponenteActionPerformed(evt);
            }
        });

        jLabel1.setText("Componente");

        jLabel2.setText("Precio");

        jLabel3.setText("Marca");

        jLabel4.setText("Descripción");

        textoDescripcionComponente.setColumns(20);
        textoDescripcionComponente.setRows(5);
        jScrollPane1.setViewportView(textoDescripcionComponente);

        jLabel5.setText("Nombre");

        botonAnadirComponente.setText("Añadir/Modificar");
        botonAnadirComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirComponenteActionPerformed(evt);
            }
        });

        botonSalirComponente.setText("Salir");
        botonSalirComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirComponenteActionPerformed(evt);
            }
        });

        jTabbedPane1.setEnabled(false);

        jLabel9.setText("Potencia");

        comboModularAlim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sí", "No" }));

        jLabel10.setText("Modular");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoPotenciaAlim, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboModularAlim, 0, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textoPotenciaAlim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboModularAlim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Alimentación", jPanel4);
        jPanel4.getAccessibleContext().setAccessibleName("");

        jLabel11.setText("Sockets");

        jLabel12.setText("Cores");

        jLabel13.setText("Threads");

        jLabel14.setText("Frecuencia");

        jLabel15.setText("TDP");

        jLabel16.setText("Microarquitectura");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoSocketsCpu)
                    .addComponent(textoCoresCpu)
                    .addComponent(textoThreadsCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoMicroCpu)
                    .addComponent(textoTdpCpu)
                    .addComponent(textoFrecuenciaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSocketsCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFrecuenciaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCoresCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTdpCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoThreadsCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMicroCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CPU", jPanel5);

        comboTipoDisco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSD", "HDD" }));

        jLabel17.setText("Tipo");

        jLabel18.setText("Capacidad");

        jLabel19.setText("Velocidad");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoCapacidadDisco)
                    .addComponent(textoVelocidadDisco)
                    .addComponent(comboTipoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCapacidadDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVelocidadDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Disco duro", jPanel6);

        jlabel20.setText("Núcleos");

        jLabel21.setText("Frecuencia");

        jLabel22.setText("Proceso de fabricación");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jlabel20)
                    .addComponent(jLabel21))
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoFrecuenciaGpu)
                    .addComponent(textoProcesoGpu)
                    .addComponent(textoNucleosGpu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel20)
                    .addComponent(textoNucleosGpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFrecuenciaGpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoProcesoGpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GPU", jPanel7);

        jLabel20.setText("Tipo");

        textoTipoPerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTipoPerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel20)
                .addGap(43, 43, 43)
                .addComponent(textoTipoPerif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textoTipoPerif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Periférico", jPanel8);

        jLabel23.setText("Chipset");

        jLabel24.setText("Tamaño");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoChipsetPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTamanoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textoChipsetPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(textoTamanoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Placa base", jPanel9);

        jLabel25.setText("Tipo DDR");

        jLabel27.setText("Memoria");

        jLabel28.setText("Frecuencia");

        jLabel30.setText("Formato");

        comboTipoRam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DDR3", "DDR4" }));

        comboFormatoRam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sobremesa", "Portátil" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoMemoriaRam, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(comboTipoRam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoFrecuenciaRam, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(comboFormatoRam, 0, 1, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFrecuenciaRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(comboTipoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMemoriaRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30)
                    .addComponent(comboFormatoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RAM", jPanel10);

        jLabel26.setText("Tipo");

        jLabel29.setText("Tamaño");

        comboTipoRefri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "GPU", "Ventilador" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoRefri, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoTamanoRefri, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(textoTamanoRefri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoRefri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Refrigeración", jPanel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(30, 30, 30)
                                        .addComponent(textoNombreComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(41, 41, 41)
                                            .addComponent(textoPrecioComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(42, 42, 42)
                                            .addComponent(textoMarcaComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botonAnadirComponente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonSalirComponente)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textoNombreComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(textoMarcaComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textoPrecioComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnadirComponente)
                    .addComponent(botonSalirComponente))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Añadir Componente", jPanel2);

        jLabel6.setText("Nombre");

        jLabel7.setText("Precio");

        botonSalirPC.setText("Salir");
        botonSalirPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirPCActionPerformed(evt);
            }
        });

        botonAnadirPC.setText("Añadir");
        botonAnadirPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAnadirPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalirPC)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoNombrePC)
                    .addComponent(textoPrecioPC, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombrePC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecioPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalirPC)
                    .addComponent(botonAnadirPC))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Añadir PC", jPanel3);

        jPanel1.setToolTipText("");

        comboComponenteEjemplar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentación", "CPU", "Disco duro", "GPU", "Periférico", "Placa base", "RAM", "Refrigeración" }));
        comboComponenteEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComponenteEjemplarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaEjemplar);

        jLabel8.setText("Componente:");

        botonSalirEjemplar.setText("Salir");
        botonSalirEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirEjemplarActionPerformed(evt);
            }
        });

        botonAnadirEjemplar.setText("Añadir");
        botonAnadirEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirEjemplarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboComponenteEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAnadirEjemplar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalirEjemplar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboComponenteEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalirEjemplar)
                    .addComponent(botonAnadirEjemplar))
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("Añadir Ejemplares", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirPCActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirPCActionPerformed

    private void botonSalirComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirComponenteActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirComponenteActionPerformed

    private void botonAnadirComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirComponenteActionPerformed
        
        boolean hayNombre = (textoNombreComponente.getText() != null) && (!textoNombreComponente.getText().isEmpty());
        boolean hayPrecio = (textoPrecioComponente.getText() != null) && (!textoPrecioComponente.getText().isEmpty());
        boolean hayMarca = (textoMarcaComponente.getText() != null) && (!textoMarcaComponente.getText().isEmpty());
        boolean hayDescripcion = (textoDescripcionComponente.getText() != null) && (!textoDescripcionComponente.getText().isEmpty());
        boolean valido = hayNombre && hayPrecio && hayMarca && hayDescripcion;
        if(!valido) {
            fa.muestraExcepcion("Todos los campos deben estar llenos.");
            return;
        }
        
        try{
            Double.parseDouble(textoPrecioComponente.getText());
        }
        catch(NumberFormatException e) {
            fa.muestraExcepcion("Introduzca un número en el campo de Precio.");
            return;
        }
        
        String nombre = textoNombreComponente.getText();
        double precio = Double.parseDouble(textoPrecioComponente.getText());
        if(precio <= 0) {
            fa.muestraExcepcion("El precio no puede ser negativo.");
            return;
        }
        String marca = textoMarcaComponente.getText();
        String descripcion = textoDescripcionComponente.getText();
        
        String tipo = (String)comboComponente.getSelectedItem();
        Componente comp = null;
        switch (tipo) {
            case "Alimentación":
                tipo = "alimentacion";
                boolean hayPotencia = (textoPotenciaAlim.getText() != null) && (!textoPotenciaAlim.getText().isEmpty());
                valido = valido && hayPotencia;
                try{
                    if(Double.parseDouble(textoPotenciaAlim.getText()) <= 0) {
                        fa.muestraExcepcion("La potencia no puede ser negativa.");
                        return;
                    }
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en el campo de Potencia.");
                    return;
                }
                boolean modular;
                if(((String)comboModularAlim.getSelectedItem()).equals("Sí")) modular = true;
                else modular = false;

                comp = new Alimentacion(Double.parseDouble(textoPotenciaAlim.getText()), modular, nombre, precio, marca, descripcion);
            break;
                
            case "CPU":
                tipo = "cpus";
                boolean haySockets = (textoSocketsCpu.getText() != null) && (!textoSocketsCpu.getText().isEmpty());
                boolean hayCores = (textoCoresCpu.getText() != null) && (!textoCoresCpu.getText().isEmpty());
                boolean hayThreads = (textoThreadsCpu.getText() != null) && (!textoThreadsCpu.getText().isEmpty());
                boolean hayFrecuencia = (textoFrecuenciaCpu.getText() != null) && (!textoFrecuenciaCpu.getText().isEmpty());
                boolean hayTdp = (textoTdpCpu.getText() != null) && (!textoTdpCpu.getText().isEmpty());
                boolean hayMicro = (textoMicroCpu.getText() != null) && (!textoMicroCpu.getText().isEmpty());
                valido = valido && haySockets && hayCores && hayThreads && hayThreads && hayFrecuencia && hayTdp && hayMicro;
                try{
                    Integer.parseInt(textoCoresCpu.getText());
                    Integer.parseInt(textoThreadsCpu.getText());
                    Double.parseDouble(textoFrecuenciaCpu.getText());
                    Double.parseDouble(textoTdpCpu.getText());
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en los campos de Cores, Threads, Frecuencia y TDP.");
                    return;
                }

                comp = new CPU(textoSocketsCpu.getText(), Integer.parseInt(textoCoresCpu.getText()),
                        Integer.parseInt(textoThreadsCpu.getText()), Double.parseDouble(textoFrecuenciaCpu.getText()),
                        Double.parseDouble(textoTdpCpu.getText()), textoMicroCpu.getText(),
                        nombre, precio, marca, descripcion);
                break;
                
            case "Disco duro":
                tipo = "discosduros";
                boolean hayCapacidad = (textoCapacidadDisco.getText() != null) && (!textoCapacidadDisco.getText().isEmpty());
                boolean hayVelocidad = (textoVelocidadDisco.getText() != null) && (!textoVelocidadDisco.getText().isEmpty());

                valido = valido && hayCapacidad && hayVelocidad;
                try{
                    if(Integer.parseInt(textoCapacidadDisco.getText()) <= 0) {
                        fa.muestraExcepcion("La capacidad no puede ser negativa.");
                        return;
                    }
                    if(Double.parseDouble(textoVelocidadDisco.getText()) <= 0) {
                        fa.muestraExcepcion("La velocidad no puede ser negativa.");
                        return;
                    }
                    
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en los campos de Capacidad y Velocidad.");
                    return;
                }

                comp = new DiscoDuro((String)comboTipoDisco.getSelectedItem(),Double.parseDouble(textoVelocidadDisco.getText()),
                        Integer.parseInt(textoCapacidadDisco.getText()), nombre, precio, marca, descripcion);
                break;
                
            case "Placa base":
                tipo = "placasbase";
                boolean hayChipset = (textoChipsetPlaca.getText() != null) && (!textoChipsetPlaca.getText().isEmpty());
                boolean hayTamano = (textoTamanoPlaca.getText() != null) && (!textoTamanoPlaca.getText().isEmpty());

                valido = valido && hayChipset && hayTamano;
                try{
                    Double.parseDouble(textoTamanoPlaca.getText());
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en el campo de Tamaño.");
                    return;
                }

                comp = new PlacaBase(textoChipsetPlaca.getText(),Double.parseDouble(textoTamanoPlaca.getText()),
                        nombre, precio, marca, descripcion);
                break;
            case "GPU":
                boolean hayNucleos = (textoNucleosGpu.getText() != null) && (!textoNucleosGpu.getText().isEmpty());
                boolean hayProceso = (textoProcesoGpu.getText() != null) && (!textoProcesoGpu.getText().isEmpty());
                boolean hayFrecuencia3 = (textoFrecuenciaGpu.getText() != null) && (!textoFrecuenciaGpu.getText().isEmpty());

                valido = valido && hayNucleos && hayProceso && hayFrecuencia3;
                try{
                    if(Integer.parseInt(textoNucleosGpu.getText()) <= 0) {
                        fa.muestraExcepcion("Los núcleos deben ser positivos.");
                        return;
                    }
                    if(Double.parseDouble(textoFrecuenciaGpu.getText()) <= 0) {
                        fa.muestraExcepcion("La frecuencia debe ser positiva.");
                        return;
                    }
                    if(Integer.parseInt(textoProcesoGpu.getText()) <= 0) {
                        fa.muestraExcepcion("El proceso debe ser positivo.");
                        return;
                    }
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en los campos de Núcleos, Frecuencia y Proceso.");
                    return;
                }

                comp = new GPU(Integer.parseInt(textoNucleosGpu.getText()),Double.parseDouble(textoFrecuenciaGpu.getText()),
                        Integer.parseInt(textoProcesoGpu.getText()), nombre, precio, marca, descripcion);
                tipo = "gpus";
                
                break;
            case "Periférico":
                tipo = "perifericos";
                boolean hayTipo = (textoTipoPerif.getText() != null) && (!textoTipoPerif.getText().isEmpty());
                valido = valido && hayTipo;


                comp = new Periferico(textoTipoPerif.getText(), nombre, precio, marca, descripcion);
                break;
            case "RAM":
                tipo = "rams";
                
                boolean hayFrecuencia2 = (textoFrecuenciaRam.getText() != null) && (!textoFrecuenciaRam.getText().isEmpty());
                boolean hayMemoria = (textoMemoriaRam.getText() != null) && (!textoMemoriaRam.getText().isEmpty());

                valido = valido && hayFrecuencia2 && hayMemoria;
                try{
                    if(Double.parseDouble(textoMemoriaRam.getText()) <= 0) {
                        fa.muestraExcepcion("La memoria debe ser positiva.");
                        return;
                    }
                    if(Double.parseDouble(textoFrecuenciaRam.getText()) <= 0) {
                        fa.muestraExcepcion("La frecuencia debe ser positiva.");
                        return;
                    }
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en los campos de Memoria y Frecuencia.");
                    return;
                }

                comp = new RAM((String)comboTipoRam.getSelectedItem(), Double.parseDouble(textoMemoriaRam.getText()),
                        Double.parseDouble(textoFrecuenciaRam.getText()), (String)comboFormatoRam.getSelectedItem(),
                        nombre, precio, marca, descripcion);
                
                break;
            case "Refrigeración":
                tipo = "refrigeracion";
                boolean hayTamano2 = (textoTamanoRefri.getText() != null) && (!textoTamanoRefri.getText().isEmpty());

                valido = valido && hayTamano2;
                try{
                    Integer.parseInt(textoTamanoRefri.getText());
                }
                catch(NumberFormatException e) {
                    fa.muestraExcepcion("Introduzca un número en el campo de Tamaño.");
                    return;
                }

                comp = new Refrigeracion((String)comboTipoRefri.getSelectedItem(), Integer.parseInt(textoTamanoRefri.getText()),
                        nombre, precio, marca, descripcion);
                break;
        }
        if(!valido) {
            fa.muestraExcepcion("Todos los campos deben estar llenos.");
            return;
        }
        
        fa.anadirComponente(tipo, comp);
    }//GEN-LAST:event_botonAnadirComponenteActionPerformed

    private void botonAnadirPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirPCActionPerformed
        boolean hayNombre = (textoNombrePC.getText() != null) && (!textoNombrePC.getText().isEmpty());
        boolean hayPrecio = (textoPrecioPC.getText() != null) && (!textoPrecioPC.getText().isEmpty());
        if((!hayNombre) || (!hayPrecio)) {
            fa.muestraExcepcion("Todos los campos deben estar llenos.");
            return;
        }
        try{
            Integer.parseInt(textoPrecioPC.getText());
        }
        catch(NumberFormatException e) {
            fa.muestraExcepcion("Introduzca un número en el campo de Precio.");
            return;
        }
        
        fa.anadirPc(textoNombrePC.getText(), Integer.parseInt(textoPrecioPC.getText()));
    }//GEN-LAST:event_botonAnadirPCActionPerformed

    private void botonSalirEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirEjemplarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirEjemplarActionPerformed

    private void comboComponenteEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComponenteEjemplarActionPerformed
        String comp = (String)comboComponenteEjemplar.getSelectedItem();
        if(comp.equals("Alimentación")) comp = "alimentacion";
        else if(comp.equals("Disco duro")) comp = "discosduros";
        else if(comp.equals("CPU")) comp = "cpus";
        else if(comp.equals("Placa base")) comp = "placasbase";
        else if(comp.equals("GPU")) comp = "gpus";
        else if(comp.equals("Periférico")) comp = "perifericos";
        else if(comp.equals("RAM")) comp = "rams";
        else if(comp.equals("Refrigeración")) comp = "refrigeracion";
        
        java.util.ArrayList<String> comps = fa.consultarComponentes(comp);
        ModeloListaStrings mListaC = (ModeloListaStrings)listaEjemplar.getModel();
        mListaC.setElementos(comps);
    }//GEN-LAST:event_comboComponenteEjemplarActionPerformed

    private void botonAnadirEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirEjemplarActionPerformed
        if(listaEjemplar.getSelectedIndex() != -1) {
            String nombre = ((ModeloListaStrings)listaEjemplar.getModel()).getElementos().get(listaEjemplar.getSelectedIndex());
            fa.anadirEjemplar(nombre);
            
        }
        else fa.muestraExcepcion("Seleccione un componente al que añadir ejemplar.");
    }//GEN-LAST:event_botonAnadirEjemplarActionPerformed

    private void textoTipoPerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTipoPerifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTipoPerifActionPerformed

    private void comboComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComponenteActionPerformed
        jTabbedPane1.setSelectedIndex(comboComponente.getSelectedIndex());
    }//GEN-LAST:event_comboComponenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadirComponente;
    private javax.swing.JButton botonAnadirEjemplar;
    private javax.swing.JButton botonAnadirPC;
    private javax.swing.JButton botonSalirComponente;
    private javax.swing.JButton botonSalirEjemplar;
    private javax.swing.JButton botonSalirPC;
    private javax.swing.JComboBox comboComponente;
    private javax.swing.JComboBox comboComponenteEjemplar;
    private javax.swing.JComboBox comboFormatoRam;
    private javax.swing.JComboBox comboModularAlim;
    private javax.swing.JComboBox comboTipoDisco;
    private javax.swing.JComboBox comboTipoRam;
    private javax.swing.JComboBox comboTipoRefri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel jlabel20;
    private javax.swing.JList listaEjemplar;
    private javax.swing.JTextField textoCapacidadDisco;
    private javax.swing.JTextField textoChipsetPlaca;
    private javax.swing.JTextField textoCoresCpu;
    private javax.swing.JTextArea textoDescripcionComponente;
    private javax.swing.JTextField textoFrecuenciaCpu;
    private javax.swing.JTextField textoFrecuenciaGpu;
    private javax.swing.JTextField textoFrecuenciaRam;
    private javax.swing.JTextField textoMarcaComponente;
    private javax.swing.JTextField textoMemoriaRam;
    private javax.swing.JTextField textoMicroCpu;
    private javax.swing.JTextField textoNombreComponente;
    private javax.swing.JTextField textoNombrePC;
    private javax.swing.JTextField textoNucleosGpu;
    private javax.swing.JTextField textoPotenciaAlim;
    private javax.swing.JTextField textoPrecioComponente;
    private javax.swing.JTextField textoPrecioPC;
    private javax.swing.JTextField textoProcesoGpu;
    private javax.swing.JTextField textoSocketsCpu;
    private javax.swing.JTextField textoTamanoPlaca;
    private javax.swing.JTextField textoTamanoRefri;
    private javax.swing.JTextField textoTdpCpu;
    private javax.swing.JTextField textoThreadsCpu;
    private javax.swing.JTextField textoTipoPerif;
    private javax.swing.JTextField textoVelocidadDisco;
    // End of variables declaration//GEN-END:variables
}
